spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 6V9+HSI77VKFnb7LkOqUdHSoGhHutXeNGMOHSSTXiId++0vCOIobZ2ecyLFkAk5QPJKhWdgCEeIDTJaQ6ya4Kw==
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAPbUMCqrMF3qbrX1hOZJifg0qHdL0P1/+3Rc955QHHLLR62nOt1FUWg3MKN6LUIAUJsoHPq7ydhiPFGv7M8jPUsCAwEAAQ==

dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 10.36.147.81:2181
  protocol:
    port: 28810